extends GutTest

## BossStateMachine Story 001 — IDLE/TELEGRAPHING/ATTACKING main path.
##
## ACs covered by this file:
##   AC-01  IDLE → TELEGRAPHING on idle_timer expiry
##   AC-03  TELEGRAPHING → ATTACKING on telegraph_timer expiry
##   AC-04  ATTACKING → IDLE on _on_attack_animation_done (sequence_index advance)
##   AC-09  Init: sequence_index=0, behavior_state=IDLE
##   AC-12  attack_telegraphed signal emitted before internal_telegraph_timer is set
##
## GUT headless rules applied here:
##   - class_name is NOT resolvable at parse time for newly-created classes (the
##     global_script_class_cache is only regenerated by an editor import). Access
##     the enum/const via the preloaded script const (_BSM_SCRIPT.X), never the
##     `BossStateMachine` global. preload() bypasses the class cache entirely.
##   - Drive timers with real deltas — never pre-zero a timer. Production only
##     transitions when a positive timer is decremented across zero (the
##     `if timer > 0.0` guard intentionally ignores an already-zero timer).
##   - initialize(mock) BEFORE add_child so _ready() does not fall back to the
##     global EventBus autoload (not registered in headless GUT).

# ─── Fixtures ─────────────────────────────────────────────────────────────────

var _bsm: Node
var _mock_bus: MockEventBus

const _BSM_SCRIPT: GDScript = preload("res://scripts/feature/boss_state_machine.gd")
const _MOCK_BUS_SCRIPT: GDScript = preload("res://tests/helpers/mock_event_bus.gd")

## Phase idle delay used by the test bosses.
const _IDLE_DURATION: float = 0.5

## A delta large enough to expire any single timer in one _physics_process call.
## maxf() floors the timer at 0, so an oversized delta simply guarantees the
## decrement crosses zero and the transition fires.
const _EXPIRE_DELTA: float = 5.0


## Build a minimal valid BossData with one phase and one AttackData.
## telegraph_duration_override is always > 0 so Story 001's production path
## (override > 0) is exercised exclusively — the Story 003 fallback is never hit.
## The literal 0.8 here is a TEST FIXTURE value; it is NOT in production .gd code.
func _make_test_boss(telegraph_override: float = 0.8) -> BossData:
	var attack: AttackData = AttackData.new()
	attack.attack_type = GameEnums.AttackType.LIGHT
	attack.damage = 10.0
	attack.telegraph_duration_override = telegraph_override

	var phase: PhaseData = PhaseData.new()
	phase.phase_index = 0
	phase.idle_duration_after_attack = _IDLE_DURATION
	phase.attack_sequence = [attack]

	var boss: BossData = BossData.new()
	boss.boss_id = &"test_boss"
	boss.boss_max_hp = 100.0
	boss.phase_threshold_pct = []
	boss.phases = [phase]
	return boss


## Build a BossData with two attacks in sequence so AC-04 wrap can be tested.
func _make_two_attack_boss() -> BossData:
	var atk_a: AttackData = AttackData.new()
	atk_a.attack_type = GameEnums.AttackType.LIGHT
	atk_a.damage = 10.0
	atk_a.telegraph_duration_override = 0.8

	var atk_b: AttackData = AttackData.new()
	atk_b.attack_type = GameEnums.AttackType.HEAVY
	atk_b.damage = 20.0
	atk_b.telegraph_duration_override = 1.2

	var phase: PhaseData = PhaseData.new()
	phase.phase_index = 0
	phase.idle_duration_after_attack = _IDLE_DURATION
	phase.attack_sequence = [atk_a, atk_b]

	var boss: BossData = BossData.new()
	boss.boss_id = &"test_boss_two"
	boss.boss_max_hp = 100.0
	boss.phase_threshold_pct = []
	boss.phases = [phase]
	return boss


func before_each() -> void:
	_mock_bus = _MOCK_BUS_SCRIPT.new()
	add_child_autofree(_mock_bus)

	_bsm = _BSM_SCRIPT.new()
	# initialize() BEFORE add_child so _ready() sees a non-null _event_bus and
	# skips the global EventBus fallback (autoload not registered in headless GUT).
	_bsm.initialize(_mock_bus)
	add_child_autofree(_bsm)


# ─── Navigation helpers (drive timers naturally) ──────────────────────────────

## Decrement the idle_timer across zero → IDLE transitions to TELEGRAPHING.
func _expire_idle() -> void:
	_bsm._physics_process(_EXPIRE_DELTA)


## Decrement the telegraph_timer across zero → TELEGRAPHING transitions to ATTACKING.
func _expire_telegraph() -> void:
	_bsm._physics_process(_EXPIRE_DELTA)


# ─── AC-09: Initialization ────────────────────────────────────────────────────

func test_init_battle_sets_sequence_index_to_zero() -> void:
	_bsm.init_battle(_make_test_boss())
	assert_eq(_bsm.sequence_index, 0, "AC-09: sequence_index must be 0 after init_battle")


func test_init_battle_sets_behavior_state_to_idle() -> void:
	_bsm.init_battle(_make_test_boss())
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.IDLE,
		"AC-09: behavior_state must be IDLE after init_battle"
	)


func test_init_battle_sets_idle_timer_from_phase_data() -> void:
	_bsm.init_battle(_make_test_boss())
	assert_almost_eq(
		_bsm.idle_timer,
		_IDLE_DURATION,
		0.001,
		"AC-09: idle_timer must be set from PhaseData.idle_duration_after_attack"
	)


# ─── AC-01: IDLE → TELEGRAPHING on idle_timer expiry ─────────────────────────

func test_idle_timer_expiry_transitions_to_telegraphing() -> void:
	_bsm.init_battle(_make_test_boss())
	_expire_idle()
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.TELEGRAPHING,
		"AC-01: behavior_state must be TELEGRAPHING after idle_timer expires"
	)


func test_idle_timer_expiry_starts_telegraph_timer() -> void:
	# AC-01 + data-driven proof: timer initialised to the injected override (0.8),
	# not decremented yet (the TELEGRAPHING branch runs the frame AFTER entry).
	_bsm.init_battle(_make_test_boss(0.8))
	_expire_idle()
	assert_almost_eq(
		_bsm.internal_telegraph_timer,
		0.8,
		0.001,
		"AC-01: internal_telegraph_timer must equal the injected override (0.8)"
	)


func test_idle_timer_not_yet_expired_does_not_transition() -> void:
	_bsm.init_battle(_make_test_boss())
	# Small delta — idle_timer (0.5) stays positive, no transition.
	_bsm._physics_process(0.1)
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.IDLE,
		"idle_timer still positive — must remain IDLE"
	)


# ─── AC-12: attack_telegraphed emitted on TELEGRAPHING entry ──────────────────

func test_attack_telegraphed_emitted_on_telegraphing_entry() -> void:
	_bsm.init_battle(_make_test_boss())
	_mock_bus.attack_telegraphed_call_count = 0
	_expire_idle()
	assert_eq(
		_mock_bus.attack_telegraphed_call_count,
		1,
		"AC-12: attack_telegraphed must be emitted exactly once on TELEGRAPHING entry"
	)


func test_attack_telegraphed_payload_matches_attack_data() -> void:
	# Factory sets attack_type=LIGHT, damage=10.0.
	_bsm.init_battle(_make_test_boss())
	_expire_idle()
	assert_eq(
		_mock_bus.last_attack_telegraphed_type,
		GameEnums.AttackType.LIGHT,
		"AC-12: signal attack_type must match AttackData.attack_type (LIGHT)"
	)
	assert_almost_eq(
		_mock_bus.last_attack_telegraphed_damage,
		10.0,
		0.001,
		"AC-12: signal damage must match AttackData.damage (10.0)"
	)


## AC-12 ordering proof: _enter_state(TELEGRAPHING) emits the signal THEN starts
## the timer. Within a synchronous call this order is enforced by code structure
## (emit line precedes the timer assignment). This test confirms both effects
## occurred in the one transition: signal fired once AND timer is set.
func test_attack_telegraphed_and_timer_both_set_in_same_transition() -> void:
	_bsm.init_battle(_make_test_boss(0.8))
	_mock_bus.attack_telegraphed_call_count = 0
	_expire_idle()
	assert_eq(
		_mock_bus.attack_telegraphed_call_count,
		1,
		"AC-12: signal must have fired during this transition"
	)
	assert_gt(
		_bsm.internal_telegraph_timer,
		0.0,
		"AC-12: telegraph timer must be > 0 — set after the signal in the same _enter_state call"
	)


# ─── AC-03: TELEGRAPHING → ATTACKING on telegraph_timer expiry ───────────────

func test_telegraph_timer_expiry_transitions_to_attacking() -> void:
	_bsm.init_battle(_make_test_boss())
	_expire_idle()
	assert_eq(_bsm.behavior_state, _BSM_SCRIPT.BehaviorState.TELEGRAPHING)
	_expire_telegraph()
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.ATTACKING,
		"AC-03: behavior_state must be ATTACKING after internal_telegraph_timer expires"
	)


func test_telegraph_timer_not_yet_expired_stays_telegraphing() -> void:
	_bsm.init_battle(_make_test_boss(0.8))
	_expire_idle()  # → TELEGRAPHING, timer = 0.8
	# Small delta — 0.8 → 0.7, stays positive.
	_bsm._physics_process(0.1)
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.TELEGRAPHING,
		"internal_telegraph_timer still positive — must remain TELEGRAPHING"
	)


# ─── AC-04: ATTACKING → IDLE on animation_finished (real handler path) ───────

## Tests the REAL _on_attack_animation_done handler by calling it directly.
## This verifies sequence_index advance and IDLE transition regardless of
## whether a real AnimationPlayer is present.
func test_attack_animation_done_advances_sequence_index() -> void:
	_bsm.init_battle(_make_two_attack_boss())
	_expire_idle()
	_expire_telegraph()
	assert_eq(_bsm.behavior_state, _BSM_SCRIPT.BehaviorState.ATTACKING)
	assert_eq(_bsm.sequence_index, 0)
	_bsm._on_attack_animation_done(_BSM_SCRIPT.ANIM_ATTACK)
	assert_eq(
		_bsm.sequence_index,
		1,
		"AC-04: sequence_index must advance from 0 to 1 after first animation_done"
	)


func test_attack_animation_done_transitions_to_idle() -> void:
	_bsm.init_battle(_make_test_boss())
	_expire_idle()
	_expire_telegraph()
	assert_eq(_bsm.behavior_state, _BSM_SCRIPT.BehaviorState.ATTACKING)
	_bsm._on_attack_animation_done(_BSM_SCRIPT.ANIM_ATTACK)
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.IDLE,
		"AC-04: behavior_state must be IDLE after animation_done handler"
	)


func test_attack_animation_done_sequence_wraps_at_end() -> void:
	# Two attacks (N=2). Advance to index 1, then wrap back to 0.
	_bsm.init_battle(_make_two_attack_boss())
	_expire_idle()
	_expire_telegraph()
	_bsm._on_attack_animation_done(_BSM_SCRIPT.ANIM_ATTACK)  # idx 0 → 1, → IDLE
	assert_eq(_bsm.sequence_index, 1, "precondition: advanced to index 1")
	# Second cycle: attack at index 1, animation done wraps N=2 → 0.
	_expire_idle()
	_expire_telegraph()
	assert_eq(_bsm.behavior_state, _BSM_SCRIPT.BehaviorState.ATTACKING)
	_bsm._on_attack_animation_done(_BSM_SCRIPT.ANIM_ATTACK)
	assert_eq(
		_bsm.sequence_index,
		0,
		"AC-04 wrap: sequence_index must wrap to 0 after the last attack in the sequence"
	)


## State guard: calling _on_attack_animation_done outside ATTACKING is a no-op
## (guard is the handler's first line per ADR-0005 / control-manifest).
func test_attack_animation_done_guard_is_noop_when_not_attacking() -> void:
	_bsm.init_battle(_make_test_boss())
	assert_eq(_bsm.behavior_state, _BSM_SCRIPT.BehaviorState.IDLE)
	var idx_before: int = _bsm.sequence_index
	_bsm._on_attack_animation_done(_BSM_SCRIPT.ANIM_ATTACK)
	assert_eq(
		_bsm.behavior_state,
		_BSM_SCRIPT.BehaviorState.IDLE,
		"guard must prevent state change when called outside ATTACKING"
	)
	assert_eq(
		_bsm.sequence_index,
		idx_before,
		"guard must prevent sequence_index change when called outside ATTACKING"
	)


## Production AnimationPlayer connection path: with a real (empty) AnimationPlayer
## holding a valid "attack" clip, entering ATTACKING connects animation_finished
## with CONNECT_ONE_SHOT.
func test_anim_player_animation_finished_connected_on_attacking_entry() -> void:
	var anim_player: AnimationPlayer = AnimationPlayer.new()
	var lib: AnimationLibrary = AnimationLibrary.new()
	var clip: Animation = Animation.new()
	clip.length = 0.1
	lib.add_animation(_BSM_SCRIPT.ANIM_ATTACK, clip)
	anim_player.add_animation_library(&"", lib)
	add_child_autofree(anim_player)

	_bsm.init_battle(_make_test_boss())
	_bsm._anim_player = anim_player  # inject before entering ATTACKING

	_expire_idle()
	_expire_telegraph()  # → ATTACKING → connects the one-shot

	assert_true(
		anim_player.animation_finished.is_connected(_bsm._on_attack_animation_done),
		"production path: animation_finished must be connected when _anim_player is set"
	)
